name: 'TTEOKGUK'

on:
  pull_request:
    types: [ opened, synchronize, closed ]

jobs:
  assign:
    name: "[CI] Assign Reviewer"
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: mungmnb777, h-beeen
          ready-comment: '코드 리뷰 요청합니다 🙆 <reviewers>'
          merged-comment: '성공적으로 Merge 되었습니다. Shout out to <reviewers> :wink:'
